name: Regressivo Qazando #nome da pipeline
on: # momento que será executada
    pull_request:
        branches: [main]
jobs: # o job de execução
    cypress-run:
        runs-on: ubuntu-latest

        steps: # passos para rodar o projeto
            - name: Clonar o projeto
              uses: actions/checkout@v6

            - name: Cypress run
              uses: cypress-io/github-action@v7
              with:
                record: true
              env:
                CYPRESS_RECORD_KEY: 600a8733-d125-4c05-9efc-406cf3d88f94
